-- create folders
os.mkdir "vs"
os.mkdir "src"
os.mkdir "include"
os.mkdir "external"
os.mkdir "data"
os.mkdir "build"
os.mkdir "tests"
os.mkdir "misc"

-- name of .sln file
workspace "default-solution-name"
	location "vs" -- location of the project files generated by premake
	language "C++"
	architecture "x86_64" -- other options: x86
	systemversion "latest" -- use Win10 SDK by default

	-- configurations for the VS project
	configurations { "Debug", "Release" }

	-- settings for the debug configuration. Now all the settings will be set for this config only
	filter { "configurations:Debug" }
		symbols "On"

	-- settings for the release configuration. Now all the settings will be set for this config only
	filter { "configurations:Release" }
		optimize "On" 

	-- reset the filter
	filter { }

	targetdir ("build/bin/%{prj.name}/%{cfg.longname}")
	objdir ("build/obj/%{prj.name}/%{cfg.longname}")

-- name of .prj file
project "default-project-name"
	kind "WindowedApp" -- other options: StaticLib, ConsoleApp

	-- specify the filters in VS project
	vpaths {
		["Headers"] = { "include/**.h" },
		["Sources"] = { "src/**.cpp" }
	}

	-- specify the files of the project. ** means get everything in all subdirs
	files { "include/**.h", "src/**.cpp" }
